{% set name = "tomli" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomli-{{ version }}.tar.gz
  sha256: c292c34f58502a1eb2bbb9f5bbc9a5ebc37bee10ffb8c2d6bbdfa8eb13cc14e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    # Cannot use flit-core >3.3.0 due to cyclic dependency
    - flit-core 3.3.0
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - tomli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hukkin/tomli
  summary: A simple TOML parser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
